#!/bin/bash
gcc -S -masm=intel $CFILE

8.UNIX is basically a simple operating system, but you have to be a genius to understand the simplicity

#include <stdio.h>
#include <unistd.h>
/**
 * main - A C program that prints a line to the standard error
 * Return: 1 (Success)
 */
int main(void)
{
fputs("and that piece of art is useful\" - Dora Korpar, 2015-10-19\n", stdout);
return (1);
}
